### ISSUE TITLE
Todo / Ideas / Meta

### ISSUE THREAD

**Issue by d-k-bo** [d-k-bo/televido#7]
## UI/UX

- [ ] the app icon needs some polish (especially the "screen" part looks very basic)

### Live view

- [ ] allow removing and reordering channels (zapp supports this)

### Mediathek view

- [ ] better channel filtering
  - instead of being a "search in" category, the channel should be an additional filter
  - mediathekviewweb api supports this by combining multiple queries
  
## Project management

- [ ] find a good release workflow
  - investigate if [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) could help here
- [ ] work closer with the MediathekView project
- [ ] https://github.com/d-k-bo/televido/issues/5

**Comment by d-k-bo** [comment]
I'm certainly most interested in implementing "better channel filtering" for now, since that has the largest impact on usability in my opinion. I don't know when I will do it, since I'm also working on other side projects.

**Comment by boernsen-development** [comment]
I think it would be very helpful to add some suggestions/recommendations to the FAQ on how to actually use Televido in common use cases. It took me quiet some time to figure out how to use it on Kubuntu. I still don't get why it can't play video itself or at least use the most commonly installed VLC player as I'm missing technical expertise.

Anyway, now I got it and it wasn't too hard ;)
- Use Flathub
- Install Clapper (some suggestions about compatible or recommended video players would be nice!)
- Install Televido

BTW: For me the most valuable point of Televido over other Options I found was the overview of the current live program. I know it from Zapp on Android, but I didn't find any Linux app other than Televido providing that, so maybe it's also worth to point that out in the README for marketing purposes ;) I really enjoy Televido, thank you!

**Comment by boernsen-development** [comment]
UX suggestion: double click to open a live program would also be nice (the play button is quiet small)

**Comment by d-k-bo** [comment]
> UX suggestion: double click to open a live program would also be nice (the play button is quiet small)

I'll look into it!
